"""empty message

Revision ID: b11b3ded02f7
Revises: 492c7eef4538
Create Date: 2021-06-02 10:45:23.135280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b11b3ded02f7'
down_revision = '492c7eef4538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_task_time', 'daily_target_minutes')
    op.drop_column('user', 'default_daily_target_min')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_daily_target_min', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_task_time', sa.Column('daily_target_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
