"""empty message

Revision ID: cd046d7dc0af
Revises: b11b3ded02f7
Create Date: 2021-06-18 09:05:45.269232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd046d7dc0af'
down_revision = 'b11b3ded02f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'active')
    # ### end Alembic commands ###
